# Generated by Django 4.2.4 on 2023-08-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='BookingDate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_guests',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='Inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
